### ISSUE TITLE
Tranfer photos from google

### ISSUE THREAD

**Issue by hjwang-824** [sangwoomo/instagan#10]
Hi, I had read the issue #7 and issue #8 and I want to transfer a single photo from google, since there is no mask for that photo, I need to train the pix2pix model  with the MHP dataset first. Then I should use the pix2pix model to produce a mask for that photo. Finally, I put both that photo and its mask into the pants2skirt_mhp model. Am I right?

**Comment by sangwoomo** [comment]
Hi, you are exactly right. In fact, I trained pix2pix model with CCP dataset, as it contains only one person for each image, but I guess MHP dataset would be okay too.
