### ISSUE TITLE
How to train the pix2pix model？

### ISSUE THREAD

**Issue by hjwang-824** [sangwoomo/instagan#11]
Hi，I want to train the pix2pix model to extract pants or skirts from photos of CCP dataset，and I get the matrix of pixel-level annotation of every photo，the value of matrix are the label number（0-58，as there are 59 kind of annotations， and I think there are 2 ways to train：
（1）set every pixel values of pants or skirts to 255，and the other pixel values to 0，then I can get the mask of pants or skirts;
（2）use the values of matrix to train，so the pix2pix model can learn to label the different parts of the photo. Finally use the method(1) to get the masks for insta-gan to train;

If use method(1), I think the trainning result can be very bad; 
If use method(2), the original value of annotation matrix are numbers from 0 to 58,  23 means jacket and 24 means pants,etc. As the small difference of the value lead to big difference of meaning， have you done some preprocessing to the matrix value such as multiply 5？
Or maybe you have better idea to train the pix2pix model？

**Comment by sangwoomo** [comment]
Hi, actually I simply used the method (1). I preprocessed image/masks following the [code](https://github.com/sangwoomo/instagan#generate-two-domain-datasets), and trained pix2pix models for each class (e.g., image -> skirt mask) using images as inputs and masks as targets. I unioned masks of each instances, but as CCP dataset contains only one instance, simply using the first (and only one) mask would be okay.

**Comment by sangwoomo** [comment]
To be more specific, you should change the name of directories produced by the [code](https://github.com/sangwoomo/instagan#generate-two-domain-datasets), from `trainA` & `trainA_seg` to `trainA` & `trainB`, as now the masks `trainA_seg` is the target domain.
