### ISSUE TITLE
val_seg is noting

### ISSUE THREAD

**Issue by qichenghan666** [sangwoomo/instagan#16]
I run the follow command: python ./datasets/generate_ccp_dataset.py --save_root ./datasets/jeans2skirt_ccp --cat1 jeans --cat2 skirt
but  there is noting in  ./datasets/jeans2skirt/valA_seg and valB_segs.

**Comment by sangwoomo** [comment]
Hi, CCP dataset has pixel-level annotations for train sets, but only image-level annotations for val sets. You can predict segmentations (e.g., with pix2pix) and save to such directories. Sorry for confusion!

**Comment by qichenghan666** [comment]
> Hi, CCP dataset has pixel-level annotations for train sets, but only image-level annotations for val sets. You can predict segmentations (e.g., with pix2pix) and save to such directories. Sorry for confusion!

Oh! I understand. Thank you for your timely reply.
