### ISSUE TITLE
A paper question about Figure 2 

### ISSUE THREAD

**Issue by qichenghan666** [sangwoomo/instagan#18]
I have a question when I read your paper.  In my opinion, the far right of the graph Figure 2 maybe 'Y' or not "Y", just like the way in Cyclegan. But it is 'X' or not 'X' here. Can you help me, please?

**Comment by sangwoomo** [comment]
Hi, you are exactly right. Precisely, it is 'Y' or 'not Y', but we simply did notation abuse for simplification.

**Comment by qichenghan666** [comment]
> Hi, you are exactly right. Precisely, it is 'Y' or 'not Y', but we simply did notation abuse for simplification.

Appreciate！！！
