### ISSUE TITLE
test problem

### ISSUE THREAD

**Issue by sitongsu** [sangwoomo/instagan#22]
i finished training the model and ran the `test.py`. according to your code in `test_model.py`, i guess that you use image only as the input for the generator. but the generator requests both segmentation masks and images. so i'm quiet confused about it
`def set_input(self, input):
        # we need to use single_dataset mode
        self.real_A = input['A'].to(self.device)
        self.image_paths = input['A_paths']`

**Comment by sangwoomo** [comment]
Hi, `test.py` run the test function in the `insta_gan_model.py` code. `test_model.py` is just a code for debugging. Sorry for your confusion!

**Comment by sitongsu** [comment]
> Hi, `test.py` run the test function in the `insta_gan_model.py` code. `test_model.py` is just a code for debugging. Sorry for your confusion!

thanks for your reply
