### ISSUE TITLE
weird color in preprocessing

### ISSUE THREAD

**Issue by vict0rsch** [sangwoomo/instagan#23]
For some unknown reason I can't understand, the processed images look like this, which is the `real_A` image of the first epoch

![BYLI4s5Xk6cRdykl9n4BQzmiC](https://user-images.githubusercontent.com/9283470/59501883-c99c0b00-8e9c-11e9-8cdd-75a18d75572c.png)

Any debugging clue?

**Comment by sangwoomo** [comment]
Hi, can you track the image through `data/unaligned_seg_dataset.py` and `models/insta_gan_model.py`?
