### ISSUE TITLE
Sizing GPUmemory for High resolution

### ISSUE THREAD

**Issue by gcosne** [sangwoomo/instagan#24]
**GPU memory for High resolution:**  
In the paper you present qualitative results in high resolution images, I wonder how can I size the GPU needed for 1024x768 images? Could you please share the one you used for higher resolution in the paper ?

**Comment by sangwoomo** [comment]
Hi, we only reported results for 200x300 scale of images. Extending the results for higher (1000x1000) resolution images would be an interesting future research direction! :)
