### ISSUE TITLE
Variable epoch ratio training schedule for generator and discriminator

### ISSUE THREAD

**Issue by bsahil29** [sangwoomo/instagan#25]
Is it possible to have varying epoch ratio training schedule for generator and discriminator with the current version of the code?
Like if I want to have a training schedule where the generator is trained for 1 epoch and then the discriminator is trained for 5 epochs and so on. 
Can I have a 5:1 epoch ratio training schedule for discriminator and generator?

**Comment by sangwoomo** [comment]
Hi, you may repeat line 284-292 of `insta_gan_model.py` to train discriminator 5 times.
