### ISSUE TITLE
How to interpret the context preserving loss?

### ISSUE THREAD

**Issue by wtupc96** [sangwoomo/instagan#29]
Hello, I really appreciate the awesome instaGAN you guys put forward. However, when I read your paper, I found something confusing about the losses: the L_cyc and L_idt cannot prevent the G to make shortcuts like learning a identity mapping(x==y', y==x'), so you use L_ctx to prevent this shortcut. But if G still learn the identity mapping, it does not hurt L_ctx and it will still be zero.

**Comment by sangwoomo** [comment]
Hi, all of the content losses (L_cyc, L_idt, L_ctx) are designed to preserve the original content while changing the style, rather than preventing the trivial solution (of identity mapping). Since GAN loss enforces network to change the style of images, it will not learn the identity mapping.

**Comment by wtupc96** [comment]
@sangwoomo I see, thanks!
