### ISSUE TITLE
RuntimeError: enc_img and enc_segs_sum do not match expect dimension 1 in networks.py

### ISSUE THREAD

**Issue by hblflybird** [sangwoomo/instagan#3]
If we set opt.batch_size > 1, feat = torch.cat([enc_img, enc_segs_sum], dim=1) raise RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1

**Comment by sangwoomo** [comment]
Hello hblflybird, currently our code only supports a single batch for one GPU.
For multi-batch experiments, you may use multi-GPUs, by using `--gpu_ids 0,1,2,3`.
As we used as large images as possible, we could load at most one image in our GPU (of 12GB).
We may fix this issue later. Thanks!
