### ISSUE TITLE
How to use Multi-GPU?

### ISSUE THREAD

**Issue by chaipangpang** [sangwoomo/instagan#30]
Hello，thanks for contributing such a good project.
I noticed parameter of ‘gpu_ids’ could be set multi GPU (ie 0,1,2). But  argument of ‘batch_size’ default 1, multi GPU does not work in this case.
So, should I set  batch_size =4 if set ‘gpu_ids’ is '0,1,2,3'？

**Comment by sangwoomo** [comment]
Hi, you are exactly right. You should set batch_size=4 for 4 gpus (0,1,2,3).
