### ISSUE TITLE
Instagan in Google Colab

### ISSUE THREAD

**Issue by muxgt** [sangwoomo/instagan#33]
Hi! Is it possible to run Instagan in Google Colab? I've got a problem of running visdom server in colab. Seems that it's not allowed by Google. What is a possible solution? Much thanks in advance!

**Comment by sangwoomo** [comment]
Hi, you have to turn off the visdom option. Can you try to put argument `--display_id 0`?

**Comment by muxgt** [comment]
Thank you! I've added this argument but got another error:
RuntimeError: output with shape [1, 300, 200] doesn't match the broadcast shape [3, 300, 200]
How can I correct it? Sorry, I'me quite new to Python, trying to learn.

**Comment by muxgt** [comment]
Found an answer here in the previous issues!
It seems to work but is there a way to visualize progress without visdom server?

**Comment by sangwoomo** [comment]
Hi, sorry for late response.
You can see `./checkpoints/experiment_name/web` directory to see progressing examples.

**Comment by muxgt** [comment]
Thank you!
