### ISSUE TITLE
Incorrect image channels for segmentation?

### ISSUE THREAD

**Issue by Sean-S-Wang** [sangwoomo/instagan#38]
Hi,
I'm getting this runtime error during training on line 71 of unaligned_seg_dataset.py

RuntimeError: output with shape [1, 200, 200] doesn't match the broadcast shape [3, 200, 200]

It looks like there is a transform being applied to the segmentation mask that doesn't match the correct dimensions. Segmentation masks are 8-bit 1 channel gray image, while training images are 24-bit 3 channel RGB.

**Comment by Sean-S-Wang** [comment]
I'm able to go around the issue by changing this line of code, but I haven't given much thought as to if that would mess up the model. Any advice?

``` bash
@@ -38,7 +38,7 @@ class UnalignedSegDataset(BaseDataset):
                for i in range(self.max_instances):
                        path = seg_path.replace('.png', '_{}.png'.format(i))
                        if os.path.isfile(path):
-                               seg = Image.open(path).convert('L')
+                               seg = Image.open(path).convert('RGB')
                                seg = self.fixed_transform(seg, seed)
```

**Comment by sangwoomo** [comment]
Hi, I think it is torchvision version problem (see Issue https://github.com/sangwoomo/instagan/issues/19 and https://github.com/sangwoomo/instagan/issues/36). I think your solution will also work! :)
