### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 44.00 MiB (GPU 0; 8.00 GiB total capacity; 5.54 GiB already allocated; 17.75 MiB free; 420.44 MiB cached)

### ISSUE THREAD

**Issue by xuujunn** [sangwoomo/instagan#39]

**Comment by xuujunn** [comment]
when the training your code, tracking in this problem,  can do solve it?

**Comment by xuujunn** [comment]
What should I do when I run into this problem while training?

**Comment by Sean-S-Wang** [comment]
I believe you just need more VRAM. I get the same error on my laptop where the GPU only has 4GB VRAM. If I run it on a beefier GPU within an identical conda environment, I do not get the error.

**Comment by xuujunn** [comment]
My environment is 2080, generally speaking, run this program should be no problem.

**Comment by sangwoomo** [comment]
Hi, can you try to use smaller image size?

**Comment by xuujunn** [comment]
Thank your reply,  this method i also tried, but show the same error

**Comment by sangwoomo** [comment]
Is this a memory leak problem or just the model size is too big? Using small images (e.g, 20x30) should not suffer from the issue in theory.

**Comment by xuujunn** [comment]
change the loadsize and finesize of base_option.py directly?

**Comment by sangwoomo** [comment]
Yes that is what I intended.

**Comment by xuujunn** [comment]
if so,  the resolution of generated image  will get worse?  Is there another solution? Thanks

**Comment by sangwoomo** [comment]
Yes, the generator will produce images with same size of the cropped image. You'd better to check the size of inputs and outputs (they can differ due do the error of division).

**Comment by xuujunn** [comment]
To solve the above problem, I set the loadsize and finesize to the same,  both are 128*128, Is that OK?

**Comment by sangwoomo** [comment]
Yes, does it work now?

**Comment by xuujunn** [comment]
training now , It takes about sixty hours . Thank you so much !!!
