### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by muthiyanbhushan** [sangwoomo/instagan#42]
Hello,

When I start training the model on the existing dataset downloaded as per the instructions. I get an error mismatch output shape.

RuntimeError: output with shape [1, 240, 160] doesn't match the broadcast shape [3, 240, 160]

I think this error has to do with the output layer. Please let me know which file should I change to make this working.
Thank you.

![InstaGAN](https://user-images.githubusercontent.com/14231146/71606506-34095580-2b26-11ea-955d-8d995482139b.png)

**Comment by sangwoomo** [comment]
Hi, sorry for version mismatch. See issue https://github.com/sangwoomo/instagan/issues/36.
