### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kalai2033** [sangwoomo/instagan#47]
Getting the above when trying to run the instaGan model. I found a similar closed issue. Where you asked to print the seg_paths variable and check for segmentation pairs. I have segmentation images for all input images both in train_A and train_B, but it still not working.

**Comment by sangwoomo** [comment]
I reopened this issue https://github.com/sangwoomo/instagan/issues/20, hence I close this issue for conciseness.
