### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by phyuphyuthaw** [sangwoomo/instagan#5]
![error2](https://user-images.githubusercontent.com/46488001/50880283-cacb8800-1392-11e9-8f3e-a73f6e41419a.JPG)

I am just training my dataset with this instagan model. my training dataset has 14221 images and at the first trial, it has error as show in figure when iter value is 4200. Second trial, now it stopped when iter value is 8900. It has increased a lot than the first trial. I am just adding my dataset folder under the directory /instagan/datasets.

**Comment by sangwoomo** [comment]
Hi phyuphyuthaw, it seems that there is an image which does not have a corresponding mask.
Currently the code assumes that every image has **at least one** corresponding mask.
Can you remove such unmatched image and try the code again please?

**Comment by phyuphyuthaw** [comment]
I tried to update my dataset and trained it again. While it was running, there was error like "packet_write_wait: Connection to <myserver> port 22: Broken pipe.. So I stopped running and then restart to train but now it says "visdom.ConnectionError: Error connecting to Visdom server" 
How can I fix them again??

**Comment by sangwoomo** [comment]
Are you using `python -m visdom.server`?
If you don't want to use the visdom server, add `--display_id 0` to your configuration.
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/333
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/230

**Comment by phyuphyuthaw** [comment]
yeah. I wrote the command python -m visdom.server. And in the other terminal, the code is running well now. While it is training, can I test my dataset in next terminal? Or do I need to wait till the training is finished?

**Comment by phyuphyuthaw** [comment]
Excuse me, list index out of range error is still happening, but not in the same iters value. once, I had 12000 iters value and then stopped there. My dataset has been checked and I think there is no more error in my dataset. could you please give me an advice on this case?

**Comment by sangwoomo** [comment]
1. You only need to turn on **one** visdom server. If the visdom server is running, you can run arbitrary many train or test experiments. I recommend to run the server in the **tmux** session.
2. The problematic part can be changed for every experiment, as the training set is randomly shuffled. In my experience, there are some broken images that the Python library (PIL) fails to read. Can you print which `seg_path` is problematic, e.g., by adding `print(seg_path)` to `UnalignedSegDataset.read_segs` method?

**Comment by phyuphyuthaw** [comment]
thank you very much. here is another problem too.


initialize network with normal
initialize network with normal
model [InstaGANModel] was created
loading the model from ./checkpoints/pp/latest_net_G_A.pth
loading the model from ./checkpoints/pp/latest_net_G_B.pth
---------- Networks initialized -------------
[Network G_A] Total number of parameters : 26.815 M
[Network G_B] Total number of parameters : 26.815 M
-----------------------------------------------
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    model.test()
  File "/Disk2/kaoru/related_works/instagan/models/insta_gan_model.py", line 188, in test
    self.real_B_img_sng = self.fake_A_img_sng.detach()
AttributeError: InstaGANModel instance has no attribute 'fake_A_img_sng'

**Comment by sangwoomo** [comment]
It seams that some of your testB images do not have corresponding masks, hence self.forward_B had never been run. Currently, the code assumes that every image have at least one corresponding mask.

**Comment by sangwoomo** [comment]
In addition, can you open a new issue for a new question please? It would help others to find the solution for the same issue, by searching the titles of the issues.
