### ISSUE TITLE
where can I download the pre-train model?

### ISSUE THREAD

**Issue by sunshinewhy** [sangwoomo/instagan#50]
Excuse me! Thanks for your excellent work. I want to download the pre-train model in your paper. Can you give it to me?

**Comment by sangwoomo** [comment]
Hi, the pre-trained models are in this link
https://drive.google.com/drive/folders/1xb9rR21MhMVselc6HTmOr73WOkOviFmO

**Comment by sunshinewhy** [comment]
Thanks!
