### ISSUE TITLE
please find function f_GX

### ISSUE THREAD

**Issue by eat-toast** [sangwoomo/instagan#6]
![image](https://user-images.githubusercontent.com/31301664/50905939-57477a80-1467-11e9-9d4f-f07af14b7157.png)

First, thank you for good quailty paper. 
I read this paper with admire to you

But I have a question. 
Where can I find functions that f_GX, f_GA (Figure 2, in red box)

Thanks.

**Comment by sangwoomo** [comment]
Hi eat-toast, thank you for reading our paper!
f_GX, f_GA (and also g, h) are defined in the **second paragraph** of Section 2.1, above the Equation (1).
In our implementation, f, g indicates the encoder and decoder, respectively.
