### ISSUE TITLE
At least one mask？

### ISSUE THREAD

**Issue by hjwang-824** [sangwoomo/instagan#8]
As the code assumes that every image has at least one corresponding mask, how can you get the Results on YouTube-searched videos (pants->skirt) and the Results on Google-searched images (pants->skirt)?

**Comment by sangwoomo** [comment]
Hi, we trained a pix2pix model to predict masks for such datasets.
But you can easily reproduce it: as I mentioned in https://github.com/sangwoomo/instagan/issues/7#issuecomment-453134692, put your images and masks in trainA/trainB respectively, and simply run
```
python train.py --dataroot ./datasets/your_dataset --name your_dataset_pix2pix --model pix2pix
```

**Comment by hjwang-824** [comment]
wow！Thank you so much
